server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/walterauth?createDatabaseIfNotExist=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8   #korisnici


    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

